const data = [
    {
        id: 1,
        image: "https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original.svg",
        title: "HTML Tutorial",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        category: "frontend",
    },
    {
        id: 2,
        image: "https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original.svg",
        title: "CSS Tutorial",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        category: "frontend",
    },
    {
        id: 3,
        image: "https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg",
        title: "JS Tutorial",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        category: "frontend",
    },
    {
        id: 4,
        image: "https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original.svg",
        title: "React Js Tutorial",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        category: "frontend",
    },
    {
        id: 5,
        image: "https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain.svg",
        title: "Bootstrap Tutorial",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        category: "frontend",
    },
    {
        id: 6,
        image: "https://raw.githubusercontent.com/devicons/devicon/master/icons/php/php-original.svg",
        title: "PHP Tutorial",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        category: "backend",
    },
    {
        id: 7,
        image: "https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original.svg",
        title: "Node.js Tutorial",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        category: "backend",
    },
    {
        id: 8,
        image: "https://raw.githubusercontent.com/devicons/devicon/master/icons/dot-net/dot-net-original.svg",
        title: "ASP Tutorial",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        category: "backend",
    },
    {
        id: 9,
        image: "https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original.svg",
        title: "SQL Tutorial",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        category: "database",
    },
    {
        id: 10,
        image: "https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original.svg",
        title: "Mongo DB Tutorial",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        category: "database",
    },
    {
        id: 11,
        image: "https://raw.githubusercontent.com/devicons/devicon/master/icons/c/c-original.svg",
        title: "C Tutorial",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        category: "programming",
    },
    {
        id: 12,
        image: "https://raw.githubusercontent.com/devicons/devicon/master/icons/cplusplus/cplusplus-original.svg",
        title: "C++ Tutorial",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        category: "programming",
    },
    {
        id: 13,
        image: "https://raw.githubusercontent.com/devicons/devicon/master/icons/java/java-original.svg",
        title: "Java Tutorial",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        category: "programming",
    },
    {
        id: 14,
        image: "https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg",
        title: "Python Tutorial",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        category: "programming",
    },
    {
        id: 15,
        image: "https://raw.githubusercontent.com/devicons/devicon/master/icons/go/go-original.svg",
        title: "Go Tutorial",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        category: "programming",
    },
];

export default data;
